Importar libreria de pandas

In [1]:
import pandas as pd

Cargamos el archivo CSV

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

Cargamos las primeras filas del dataset usando [df.head] sirve para mostrar las primeras 5 filas de un dataset

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/kevinnumanzor17/Kevin_Umanzor_2522192022/refs/heads/main/Dataset/clave_I_agrupacion.csv")
df.head()

,registro_id,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
0,I-R0155,41,1855,8.60,192.15,8.53,1,52
1,I-R0116,33,994,6.04,62.84,9.40,1,18
2,I-R0233,43,807,2.94,73.22,4.81,3,12
3,I-R0167,52,1528,9.44,157.53,7.15,12,54
4,I-R0108,27,1169,6.04,92.08,7.97,1,7

Verificamos los valores nulos duplicados y tipos de datos

nulos

In [4]:
df.isnull().sum()

registro_id         0
edad                0
ingresos            0
frecuencia_uso      0
gasto_promedio      0
satisfaccion        1
reclamos            0
antiguedad_meses    0
dtype: int64

Duplicados

In [5]:
df.info()
print(df.duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   registro_id       262 non-null    object
 1   edad              262 non-null    int64
 2   ingresos          262 non-null    int64
 3   frecuencia_uso    262 non-null    float64
 4   gasto_promedio    262 non-null    float64
 5   satisfaccion      261 non-null    float64
 6   reclamos          262 non-null    int64
 7   antiguedad_meses  262 non-null    int64
dtypes: float64(3), int64(4), object(1)
memory usage: 16.5+ KB
0

tipos de datos

In [6]:
df.dtypes

registro_id          object
edad                  int64
ingresos              int64
frecuencia_uso      float64
gasto_promedio      float64
satisfaccion        float64
reclamos              int64
antiguedad_meses      int64
dtype: object

Aplicar reglas de asociación

resumen estadístico de las columnas numericas

In [7]:
df.describe()

,edad,ingresos,frecuencia_uso,gasto_promedio,satisfaccion,reclamos,antiguedad_meses
count,262.000000,262.000000,262.000000,262.000000,261.000000,262.000000,262.000000
mean,41.843511,1155.770992,5.453435,87.654542,7.001801,2.511450,19.450382
std,9.958262,444.734241,2.977220,52.055326,1.814834,1.978298,13.860395
min,18.000000,300.000000,0.000000,5.000000,2.770000,0.000000,1.000000
25%,35.000000,833.000000,3.015000,47.077500,5.610000,1.000000,8.250000
50%,42.000000,1040.500000,5.580000,78.090000,7.260000,2.000000,17.000000
75%,48.000000,1407.500000,7.797500,126.410000,8.530000,4.000000,29.000000
max,66.000000,2900.000000,12.010000,260.000000,10.000000,12.000000,57.000000

 Eliminar identificador

In [8]:
df = df.drop(columns=['registro_id'])

Crear datos binarios simples

In [9]:
df_prep = pd.DataFrame()

df_prep['Ingresos_Altos'] = df['ingresos'] > 1500
df_prep['Frecuencia_Alta'] = df['frecuencia_uso'] > 7
df_prep['Gasto_Alto'] = df['gasto_promedio'] > 120
df_prep['Satisfaccion_Alta'] = df['satisfaccion'] > 7
df_prep['Muchos_Reclamos'] = df['reclamos'] > 5

ver el resultado

In [10]:
print(df_prep.head())

   Ingresos_Altos  Frecuencia_Alta  Gasto_Alto  Satisfaccion_Alta  \
0            True             True        True               True
1           False            False       False               True
2           False            False       False              False
3            True             True        True               True
4           False            False       False               True

   Muchos_Reclamos
0            False
1            False
2            False
3             True
4            False

In [11]:
from mlxtend.frequent_patterns import fpgrowth

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

ahora se aplica "FP-Growth" este sirve para descubrir patrones frecuentes y reglas de asociación entre elementos

In [12]:
frequent_patterns = fpgrowth(
    df_prep,
    min_support=0.2,
    use_colnames=True
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Mostramos los resultados de este algoritmo que usamos:

In [13]:
print(frequent_patterns)

     support                                          itemsets
0   0.534351                               (Satisfaccion_Alta)
1   0.339695                                 (Frecuencia_Alta)
2   0.267176                                      (Gasto_Alto)
3   0.236641                                  (Ingresos_Altos)
4   0.305344              (Satisfaccion_Alta, Frecuencia_Alta)
5   0.248092                   (Satisfaccion_Alta, Gasto_Alto)
6   0.225191                     (Gasto_Alto, Frecuencia_Alta)
7   0.209924  (Gasto_Alto, Satisfaccion_Alta, Frecuencia_Alta)
8   0.229008                      (Gasto_Alto, Ingresos_Altos)
9   0.225191               (Satisfaccion_Alta, Ingresos_Altos)
10  0.209924                 (Frecuencia_Alta, Ingresos_Altos)
11  0.217557   (Gasto_Alto, Satisfaccion_Alta, Ingresos_Altos)
12  0.209924     (Gasto_Alto, Frecuencia_Alta, Ingresos_Altos)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Generar reglas de asociación usando soporte, confianza y lift.

Estas permiten descubrir relaciones ocultas y patrones frecuentes entre elementos de un dataset.

In [14]:
from mlxtend.frequent_patterns import association_rules

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Esta función analiza qué productos o eventos ocurren juntos con mayor frecuencia

gereramos una regla de asociacion

In [15]:
rules = association_rules(
    frequent_patterns,
    metric="confidence",
    min_threshold=0.5
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Mostrar soporte, confianza y lift

In [16]:
print(
    rules[['antecedents',
           'consequents',
           'support',
           'confidence',
           'lift']]
)

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

                             antecedents  \
0                    (Satisfaccion_Alta)
1                      (Frecuencia_Alta)
2                           (Gasto_Alto)
3                           (Gasto_Alto)
4                      (Frecuencia_Alta)
5        (Satisfaccion_Alta, Gasto_Alto)
6          (Frecuencia_Alta, Gasto_Alto)
7   (Frecuencia_Alta, Satisfaccion_Alta)
8                           (Gasto_Alto)
9                      (Frecuencia_Alta)
10                          (Gasto_Alto)
11                      (Ingresos_Altos)
12                      (Ingresos_Altos)
13                     (Frecuencia_Alta)
14                      (Ingresos_Altos)
15       (Satisfaccion_Alta, Gasto_Alto)
16          (Ingresos_Altos, Gasto_Alto)
17   (Ingresos_Altos, Satisfaccion_Alta)
18                          (Gasto_Alto)
19                      (Ingresos_Altos)
20         (Frecuencia_Alta, Gasto_Alto)
21          (Ingresos_Altos, Gasto_Alto)
22     (Ingresos_Altos, Frecuencia_Alta)
23                          (Gasto_Alto)
24                     (Frecuencia_Alta)
25                      (Ingresos_Altos)

                             consequents   support  confidence      lift
0                      (Frecuencia_Alta)  0.305344    0.571429  1.682183
1                    (Satisfaccion_Alta)  0.305344    0.898876  1.682183
2                    (Satisfaccion_Alta)  0.248092    0.928571  1.737755
3                      (Frecuencia_Alta)  0.225191    0.842857  2.481220
4                           (Gasto_Alto)  0.225191    0.662921  2.481220
5                      (Frecuencia_Alta)  0.209924    0.846154  2.490925
6                    (Satisfaccion_Alta)  0.209924    0.932203  1.744552
7                           (Gasto_Alto)  0.209924    0.687500  2.573214
8   (Frecuencia_Alta, Satisfaccion_Alta)  0.209924    0.785714  2.573214
9        (Satisfaccion_Alta, Gasto_Alto)  0.209924    0.617978  2.490925
10                      (Ingresos_Altos)  0.229008    0.857143  3.622120
11                          (Gasto_Alto)  0.229008    0.967742  3.622120
12                   (Satisfaccion_Alta)  0.225191    0.951613  1.780876
13                      (Ingresos_Altos)  0.209924    0.617978  2.611453
14                     (Frecuencia_Alta)  0.209924    0.887097  2.611453
15                      (Ingresos_Altos)  0.217557    0.876923  3.705707
16                   (Satisfaccion_Alta)  0.217557    0.950000  1.777857
17                          (Gasto_Alto)  0.217557    0.966102  3.615981
18   (Ingresos_Altos, Satisfaccion_Alta)  0.217557    0.814286  3.615981
19       (Satisfaccion_Alta, Gasto_Alto)  0.217557    0.919355  3.705707
20                      (Ingresos_Altos)  0.209924    0.932203  3.939311
21                     (Frecuencia_Alta)  0.209924    0.916667  2.698502
22                          (Gasto_Alto)  0.209924    1.000000  3.742857
23     (Ingresos_Altos, Frecuencia_Alta)  0.209924    0.785714  3.742857
24          (Ingresos_Altos, Gasto_Alto)  0.209924    0.617978  2.698502
25         (Frecuencia_Alta, Gasto_Alto)  0.209924    0.887097  3.939311

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

Mostrar las 10 reglas más relevantes especificando cuantas imprimir

In [17]:
top_10 = rules.sort_values(by='lift', ascending=False).head(10)

print(
    top_10[['antecedents',
            'consequents',
            'support',
            'confidence',
            'lift']]
)

                            antecedents                          consequents  \
20        (Frecuencia_Alta, Gasto_Alto)                     (Ingresos_Altos)
25                     (Ingresos_Altos)        (Frecuencia_Alta, Gasto_Alto)
22    (Ingresos_Altos, Frecuencia_Alta)                         (Gasto_Alto)
23                         (Gasto_Alto)    (Ingresos_Altos, Frecuencia_Alta)
19                     (Ingresos_Altos)      (Satisfaccion_Alta, Gasto_Alto)
15      (Satisfaccion_Alta, Gasto_Alto)                     (Ingresos_Altos)
10                         (Gasto_Alto)                     (Ingresos_Altos)
11                     (Ingresos_Altos)                         (Gasto_Alto)
18                         (Gasto_Alto)  (Ingresos_Altos, Satisfaccion_Alta)
17  (Ingresos_Altos, Satisfaccion_Alta)                         (Gasto_Alto)

     support  confidence      lift
20  0.209924    0.932203  3.939311
25  0.209924    0.887097  3.939311
22  0.209924    1.000000  3.742857
23  0.209924    0.785714  3.742857
19  0.217557    0.919355  3.705707
15  0.217557    0.876923  3.705707
10  0.229008    0.857143  3.622120
11  0.229008    0.967742  3.622120
18  0.217557    0.814286  3.615981
17  0.217557    0.966102  3.615981

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)

-- explicacion de estas reglas --

se interpretaron 5 reglas con lenguaje de negocio:

(Frecuencia_Alta, Gasto_Alto) → (Ingresos_Altos)

1. Los clientes que utilizan frecuentemente el servicio y además presentan un gasto alto, generalmente pertenecen al segmento de ingresos altos. Esto indica que los clientes con mayor capacidad económica tienden a interactuar más y generar mayor consumo.

(Ingresos_Altos) → (Frecuencia_Alta, Gasto_Alto)

2. Los clientes con ingresos altos tienden a usar el servicio con mayor frecuencia y realizar gastos elevados. Esto puede ayudar a la empresa a identificar clientes premium o de alto valor.

(Ingresos_Altos, Frecuencia_Alta) → (Gasto_Alto)

3. Cuando un cliente posee ingresos altos y utiliza frecuentemente el servicio, existe una alta probabilidad de que también tenga un gasto promedio alto. Esto sugiere que la frecuencia de uso influye en el nivel de consumo.

(Ingresos_Altos) → (Satisfaccion_Alta, Gasto_Alto)

4. Los clientes con ingresos altos suelen presentar altos niveles de satisfacción y un mayor gasto promedio. Esto puede indicar que la empresa está logrando satisfacer adecuadamente a sus clientes más rentables.

(Gasto_Alto) → (Ingresos_Altos)

5. Los clientes con gastos elevados generalmente pertenecen al grupo de ingresos altos. Esto permite a la empresa identificar patrones de consumo asociados al nivel económico del cliente.

# Parte final: Proponer al menos 3 recomendaciones comerciales basadas en los resultados.

1. Implementar estrategias de fidelización para clientes de ingresos altos
Debido a que los clientes con ingresos altos presentan mayor frecuencia de uso y gasto elevado, la empresa puede crear programas de beneficios, descuentos exclusivos o membresías premium para mantener su lealtad.

2. Diseñar campañas dirigidas a clientes con alta frecuencia de uso
Los resultados muestran que los clientes que utilizan más el servicio también generan mayores gastos. Por ello, la empresa puede ofrecer promociones personalizadas o ventas cruzadas para incrementar aún más el consumo.

3. Mantener altos niveles de satisfacción en clientes de mayor valor
Se observó que los clientes con ingresos altos también presentan alta satisfacción. La empresa debería fortalecer la calidad del servicio y la atención al cliente para conservar este segmento rentable y evitar pérdida de clientes importantes.